<?php
$locations = $block->getStoreLocator();
$i = 1;
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get(\Magento\Store\Model\StoreManagerInterface::class);
$currentStore = $storeManager->getStore();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>
<div id="store_list">
    <?php foreach ($locations as $location):?>
        <div class="list" name="mapLocation" data-id="<?=/* @noEscape */ $i ?>">
            <?php
            if ($location->getImageStore()) {
                $image = $mediaUrl . json_decode($location->getImageStore());
            } else {
                $image = $block->getViewFileUrl('Codilar_StoreLocator::images/shop.jpg');
            }
            ?>
            <div class="image">
                <img src="<?=/* @noEscape */ $image ?>"/>
            </div>
            <div class="location-information">
                <h2><?= $block->escapeHtml($location->getName()); ?></h2>
                <?php if ($location->getcity() && trim($location->getCity())) { ?>
                    <div><?=/* @noEscape */ __('City') ?>: <?= $block->escapeHtml($location->getCity()); ?></div>
                <?php }?>
                <?php if ($location->getPostcode() && trim($location->getPostcode())) { ?>
                    <div><?=/* @noEscape */ __('Zip') ?>: <?= $block->escapeHtml($location->getPostcode()); ?></div>
                <?php }?>
                <?php if ($location->getCountry() && trim($location->getCountry())) { ?>
                    <div><?=/* @noEscape */ __('Country') ?>: <?= $block->escapeHtml($location->getCountry()); ?></div>
                <?php }?>
                <?php if ($location->getAddress() && trim($location->getAddress())) { ?>
                    <div><?=/* @noEscape */ __('Address') ?>: <?= $block->escapeHtml($location->getAddress()); ?></div>
                <?php }?>

                <div class="view-detail"><a href="
                <?=/* @noEscape */ $block->getUrl('store-locator/store/view/key/' . $location->getId()) ?>">
                        <?=/* @noEscape */ __('View Detail') ?></a></div>
            </div>
            <?php $time_today = $block->getTimeStoreLocator($location->getStoreId()) ?>

            <div class="all_today_time" style="display:none;">
                <?=/* @noEscape */ $block->getAllTimeStoreLocator($location->getStoreId()); ?>
            </div>
        </div>
       <?php $i++?>
    <?php endforeach; ?>
</div>
